pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/angierigalbisogni/final-devops-project.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
}
